[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'h1mesuke/unite-outline'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'
